CREATE TABLE TECHNICAL (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    telephone  VARCHAR(20) NOT NULL,
    available  BOOLEAN DEFAULT TRUE,
    username VARCHAR(100),
    FOREIGN KEY (username) REFERENCES USERS(USERNAME)
);