CREATE TABLE CLIENT (
	id BIGINT NOT NULL AUTO_INCREMENT,
	username VARCHAR(100) NOT NULL,
    name VARCHAR(200) NOT NULL,
    telephone varchar(25) NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY (username) REFERENCES USERS(USERNAME)
)