CREATE TABLE TECHNICAL_SPECIALITY(
    TECHNICAL_ID BIGINT,
    SPECIALITY_ID BIGINT,
    FOREIGN KEY (TECHNICAL_ID) REFERENCES TECHNICAL(id),
    FOREIGN KEY (SPECIALITY_ID) REFERENCES SPECIALITY(ID),
    PRIMARY KEY(TECHNICAL_ID, SPECIALITY_ID)
)