spring:
  application:
     name: analysis-ms
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/analysis_db
    username: root
    password: 021978
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
  instance:
    hostname: localhost
    non-secure-port: ${server.port}
    prefer-ip-address: true
server:
  port: 8085
  forward-headers-strategy: framework