spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/storage_db
        username: root
        password: 021978
    rabbitmq:
        host: localhost
        port: 5672
        username: admin
        password: 123456
        listener:
            simple:
                retry:
                    initial-interval: 5000
                    multiplier: 1
                    max-interval: 300000

