spring:
    application:
        name: report-documents
    rabbitmq:
        host: localhost
        port: 5672
        username: admin
        password: 123456
    data:
        mongodb:
            uri: mongodb://localhost:27017/storage-db
            auto-index-creation: true
cloud:
    aws:
        endpoint:
            uri: http://localhost:4566
        s3:
            endpoint: http://s3.localhost.localstack.cloud:4566
        region:
            static: us-east-1
        credentials:
            access-key: test
            secret-key: test
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8081/eureka