spring:
    application:
        name: storage-ms
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/storage_db
        username: root
        password: 021978
    rabbitmq:
        host: localhost
        port: 5672
        username: admin
        password: 123456
        listener:
            simple:
                retry:
                    initial-interval: 5000
                    multiplier: 1
                    max-interval: 300000

cloud:
    aws:
        endpoint:
            uri: http://localhost:4566
        s3:
            endpoint: http://s3.localhost.localstack.cloud:4566
        region:
            static: us-east-1
        credentials:
            access-key: test
            secret-key: test
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8081/eureka
    instance:
        hostname: localhost
        non-secure-port: ${server.port}
        prefer-ip-address: true
server:
    port: 8084